# Generated by Django 3.0.3 on 2020-02-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('shopName', models.CharField(default='Не указано', max_length=30, verbose_name='Название магазина')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
            ],
        ),
    ]
